#!/bin/bash
D="$HOME/bin"; mkdir -p "$D"

P="$2.tar.gz"
B="$2"

case "$1" in
    i) [ -z "$2" ] && exit 1
       wget --no-check-certificate -q --show-progress -O "$D/$P" "https://github.com/Apon77/static-bin/releases/download/v1.0.0/$2.tar.gz" && tar xzvf "$D/$P" -C "$D" && rm -f "$D/$P" ;;
    r) [ -z "$2" ] && exit 1
       for b in $B; do rm -f "$D/$b"; done ;;
    *) echo "Usage: bin [i|r] [package]" && exit 1 ;;
esac

